export default {
    shopList: {},
    shopNum: 0,
    shopState: {},
    shopName: [],
    totalPrice: 0,
    collectionList: {},
    viewedList:{},
    goodsNum: 0,
    goodsMaxNum: 99,
    selectedGood:{},
    isLogin: false,
    userInfo: {},
    address: null,
    buyNowGood:{},
}
